<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Grpc.Net.Client" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Sergin.MeterMinder.DeviceManagement.Presentation.Grpc.Contracts\Sergin.MeterMinder.DeviceManagement.Presentation.Grpc.Contracts.csproj" />
		<ProjectReference Include="..\Sergin.MeterMinder.DeviceManagement.Application.Contracts\Sergin.MeterMinder.DeviceManagement.Application.Contracts.csproj" />
		<ProjectReference Include="..\..\..\SharedKernel\Sergin.SharedKernel.Presentation.Grpc\Sergin.SharedKernel.Presentation.Grpc.csproj" />
		<ProjectReference Include="..\..\..\SharedKernel\Sergin.SharedKernel.Infrastructure\Sergin.SharedKernel.Infrastructure.csproj" />
		<ProjectReference Include="..\..\..\SharedKernel\Sergin.SharedKernel.Modules\Sergin.SharedKernel.Modules.csproj" />
	</ItemGroup>

</Project>
